import { Project, Task } from '@/types';

export const mockProjects: Project[] = [
  {
    id: '1',
    userId: 'user1',
    name: '6-Axis Robot Arm',
    description: 'Design and assembly of a 3D printed 6-axis robotic arm with stepper motors.',
    type: 'physical',
    status: 'active',
    budget: 5000,
    spent: 3450,
    startDate: new Date('2023-11-01'),
    deadline: new Date('2024-02-01'),
    progress: 65,
    tags: ['robotics', '3d-printing', 'arduino'],
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-12-10'),
  },
  {
    id: '2',
    userId: 'user1',
    name: 'E-Commerce Platform',
    description: 'Full-stack e-commerce solution with Next.js and specialized inventory management.',
    type: 'software',
    status: 'planning',
    budget: 0,
    spent: 0,
    startDate: new Date('2023-12-15'),
    progress: 10,
    githubRepo: {
      id: 12345,
      name: 'ecommerce-next',
      url: 'https://github.com/turha/ecommerce-next',
      owner: 'turha',
      openIssuesCount: 3
    },
    tags: ['nextjs', 'react', 'ecommerce'],
    createdAt: new Date('2023-12-05'),
    updatedAt: new Date('2023-12-05'),
  },
  {
    id: '3',
    userId: 'user1',
    name: 'Home Automation Hub',
    description: 'Central control unit for smart home devices using ESP32.',
    type: 'personal',
    status: 'on-hold',
    budget: 1000,
    spent: 250,
    startDate: new Date('2023-09-01'),
    progress: 30,
    tags: ['iot', 'esp32', 'home-automation'],
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-10-15'),
  }
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    projectId: '1',
    title: 'Print Base Gear',
    description: 'Print the main base gear using PETG filament.',
    status: 'done',
    priority: 'high',
    isGithubIssue: false,
    subtasks: [],
    createdAt: new Date('2023-11-05'),
    updatedAt: new Date('2023-11-06'),
  },
  {
    id: 't2',
    projectId: '1',
    title: 'Motor Calibration',
    description: 'Calibrate all 6 stepper motors ensuring correct steps/mm.',
    status: 'in-progress',
    priority: 'critical',
    isGithubIssue: false,
    subtasks: [
      { id: 'st1', title: 'Axis 1', done: true },
      { id: 'st2', title: 'Axis 2', done: true },
      { id: 'st3', title: 'Axis 3', done: false },
    ],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2023-12-11'),
  },
  {
    id: 't3',
    projectId: '2',
    title: 'Setup Database Schema',
    status: 'todo',
    priority: 'high',
    isGithubIssue: true,
    githubIssueId: 42,
    githubIssueUrl: 'https://github.com/turha/ecommerce-next/issues/42',
    subtasks: [],
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2023-12-10'),
  }
];
